"""Skill knowledge graph HTTP surface.

Routers stay thin: they validate, delegate to the service, and serialise.
Graph traversal, sequencing and cycle prevention are computed deterministically
in `SkillGraphService` — never generated by a model.
"""

from __future__ import annotations

import uuid

from fastapi import APIRouter, Query, status

from app.core.deps import AdminUser, CurrentUser, PaginationDep, SessionDep
from app.schemas.common import Page
from app.schemas.skill import (
    CycleReport,
    DependentEdgeRead,
    LearningSequenceRequest,
    LearningSequenceResponse,
    PrerequisiteCreate,
    PrerequisiteEdgeRead,
    PrerequisiteRead,
    PrerequisiteTreeResponse,
    PrerequisiteUpdate,
    SkillCategoryCreate,
    SkillCategoryRead,
    SkillCategoryUpdate,
    SkillCreate,
    SkillDependencyAnalysis,
    SkillGraphResponse,
    SkillRead,
    SkillUpdate,
    ValidateOrderRequest,
    ValidateOrderResponse,
)
from app.services.skill_graph_service import SkillGraphService
from app.services.skill_service import SkillCategoryService, SkillService

router = APIRouter(prefix="/skills", tags=["skills"])
categories_router = APIRouter(prefix="/skill-categories", tags=["skills"])
prerequisites_router = APIRouter(prefix="/prerequisites", tags=["skills"])


# --- categories ------------------------------------------------------------
@categories_router.get("", response_model=list[SkillCategoryRead])
async def list_categories(session: SessionDep, _: CurrentUser) -> list[SkillCategoryRead]:
    items = await SkillCategoryService(session).list()
    return [SkillCategoryRead.model_validate(c) for c in items]


@categories_router.post(
    "", response_model=SkillCategoryRead, status_code=status.HTTP_201_CREATED
)
async def create_category(
    payload: SkillCategoryCreate, session: SessionDep, _: AdminUser
) -> SkillCategoryRead:
    return SkillCategoryRead.model_validate(await SkillCategoryService(session).create(payload))


@categories_router.patch("/{category_id}", response_model=SkillCategoryRead)
async def update_category(
    category_id: uuid.UUID, payload: SkillCategoryUpdate, session: SessionDep, _: AdminUser
) -> SkillCategoryRead:
    return SkillCategoryRead.model_validate(
        await SkillCategoryService(session).update(category_id, payload)
    )


@categories_router.delete(
    "/{category_id}", status_code=status.HTTP_204_NO_CONTENT, response_model=None
)
async def delete_category(category_id: uuid.UUID, session: SessionDep, _: AdminUser) -> None:
    await SkillCategoryService(session).delete(category_id)


# --- skills ----------------------------------------------------------------
@router.get("", response_model=Page[SkillRead])
async def list_skills(
    session: SessionDep,
    pagination: PaginationDep,
    _: CurrentUser,
    search: str | None = Query(default=None, min_length=1, max_length=128),
    category_id: uuid.UUID | None = None,
    category: str | None = Query(default=None, description="Filter by category slug"),
    domain: str | None = None,
    min_difficulty: int | None = Query(default=None, ge=1, le=5),
    max_difficulty: int | None = Query(default=None, ge=1, le=5),
    is_active: bool | None = True,
) -> Page[SkillRead]:
    items, total = await SkillService(session).list(
        limit=pagination.limit,
        offset=pagination.offset,
        search=search,
        category_id=category_id,
        category_slug=category,
        domain=domain,
        min_difficulty=min_difficulty,
        max_difficulty=max_difficulty,
        is_active=is_active,
    )
    return Page[SkillRead](
        items=[SkillRead.model_validate(s) for s in items],
        total=total,
        limit=pagination.limit,
        offset=pagination.offset,
    )


@router.post("", response_model=SkillRead, status_code=status.HTTP_201_CREATED)
async def create_skill(payload: SkillCreate, session: SessionDep, _: AdminUser) -> SkillRead:
    return SkillRead.model_validate(await SkillService(session).create(payload))


# --- graph-wide operations (registered before /{skill_id} to avoid capture) -
@router.post(
    "/learning-sequence",
    response_model=LearningSequenceResponse,
    summary="Deterministic prerequisite-aware order covering the target skills",
)
async def find_learning_sequence(
    payload: LearningSequenceRequest, session: SessionDep, _: CurrentUser
) -> LearningSequenceResponse:
    return await SkillGraphService(session).find_learning_sequence(payload)


@router.post(
    "/validate-order",
    response_model=ValidateOrderResponse,
    summary="Validate a proposed learning order against the prerequisite graph",
)
async def validate_learning_order(
    payload: ValidateOrderRequest, session: SessionDep, _: CurrentUser
) -> ValidateOrderResponse:
    return await SkillGraphService(session).validate_learning_order(payload.skill_ids)


@router.get(
    "/graph/cycles",
    response_model=CycleReport,
    summary="Integrity check: report any prerequisite cycles in the whole graph",
)
async def detect_cycles(session: SessionDep, _: AdminUser) -> CycleReport:
    return await SkillGraphService(session).detect_cycles()


@router.get("/{skill_id}", response_model=SkillRead)
async def get_skill(skill_id: uuid.UUID, session: SessionDep, _: CurrentUser) -> SkillRead:
    return SkillRead.model_validate(await SkillGraphService(session).get_skill(skill_id))


@router.patch("/{skill_id}", response_model=SkillRead)
async def update_skill(
    skill_id: uuid.UUID, payload: SkillUpdate, session: SessionDep, _: AdminUser
) -> SkillRead:
    return SkillRead.model_validate(await SkillService(session).update(skill_id, payload))


@router.delete("/{skill_id}", status_code=status.HTTP_204_NO_CONTENT, response_model=None)
async def delete_skill(skill_id: uuid.UUID, session: SessionDep, _: AdminUser) -> None:
    await SkillService(session).delete(skill_id)


# --- per-skill graph views -------------------------------------------------
@router.get(
    "/{skill_id}/prerequisites",
    response_model=list[PrerequisiteEdgeRead],
    summary="Direct prerequisites of a skill (what it requires)",
)
async def list_prerequisites(
    skill_id: uuid.UUID,
    session: SessionDep,
    _: CurrentUser,
) -> list[PrerequisiteEdgeRead]:
    edges = await SkillGraphService(session).get_prerequisites(skill_id)
    return [PrerequisiteEdgeRead.model_validate(e) for e in edges]


@router.get(
    "/{skill_id}/dependents",
    response_model=list[DependentEdgeRead],
    summary="Skills that directly require this one",
)
async def list_dependents(
    skill_id: uuid.UUID, session: SessionDep, _: CurrentUser
) -> list[DependentEdgeRead]:
    edges = await SkillGraphService(session).get_dependents(skill_id)
    return [DependentEdgeRead.model_validate(e) for e in edges]


@router.get(
    "/{skill_id}/dependencies",
    response_model=SkillDependencyAnalysis,
    summary="Full dependency analysis: closure, critical path, levels, sequence",
)
async def calculate_dependencies(
    skill_id: uuid.UUID, session: SessionDep, _: CurrentUser
) -> SkillDependencyAnalysis:
    return await SkillGraphService(session).calculate_skill_dependencies(skill_id)


@router.get(
    "/{skill_id}/prerequisite-tree",
    response_model=PrerequisiteTreeResponse,
    summary="Nested prerequisite tree (shared sub-trees expanded once)",
)
async def prerequisite_tree(
    skill_id: uuid.UUID,
    session: SessionDep,
    _: CurrentUser,
    max_depth: int = Query(default=12, ge=1, le=12),
) -> PrerequisiteTreeResponse:
    return await SkillGraphService(session).get_prerequisite_tree(skill_id, max_depth=max_depth)


@router.get(
    "/{skill_id}/graph",
    response_model=SkillGraphResponse,
    summary="Transitive prerequisite closure as a flat node/edge list",
)
async def skill_graph(
    skill_id: uuid.UUID,
    session: SessionDep,
    _: CurrentUser,
    depth: int = Query(default=16, ge=1, le=32),
) -> SkillGraphResponse:
    return await SkillGraphService(session).closure_graph(skill_id, depth)


@router.post(
    "/{skill_id}/prerequisites",
    response_model=PrerequisiteRead,
    status_code=status.HTTP_201_CREATED,
    summary="Add a prerequisite edge (rejected if it would create a cycle)",
)
async def add_prerequisite(
    skill_id: uuid.UUID, payload: PrerequisiteCreate, session: SessionDep, _: AdminUser
) -> PrerequisiteRead:
    edge = await SkillGraphService(session).add_prerequisite(
        payload.model_copy(update={"source_skill_id": skill_id})
    )
    return PrerequisiteRead.model_validate(edge)


# --- prerequisite edge mutation --------------------------------------------
@prerequisites_router.patch("/{edge_id}", response_model=PrerequisiteRead)
async def update_prerequisite(
    edge_id: uuid.UUID, payload: PrerequisiteUpdate, session: SessionDep, _: AdminUser
) -> PrerequisiteRead:
    edge = await SkillGraphService(session).update_prerequisite(edge_id, payload)
    return PrerequisiteRead.model_validate(edge)


@prerequisites_router.delete(
    "/{edge_id}", status_code=status.HTTP_204_NO_CONTENT, response_model=None
)
async def delete_prerequisite(edge_id: uuid.UUID, session: SessionDep, _: AdminUser) -> None:
    await SkillGraphService(session).delete_prerequisite(edge_id)
