"""initial schema

Revision ID: 6b23d77231f9
Revises: 
Create Date: 2026-08-18 22:29:04.597897
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = '6b23d77231f9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Extensions first: `vector` backs the embedding columns, `pgcrypto`
    # provides gen_random_uuid() used as the server-side id default, `pg_trgm`
    # backs fuzzy search on skill names and titles. Compose also creates these
    # via infra/postgres/init.sql; repeating them keeps `alembic upgrade head`
    # sufficient on a database provisioned some other way.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('type', sa.Enum('course', 'project', 'article', 'video', 'book', 'tutorial', 'lab', 'assessment', name='resource_type'), nullable=False),
    sa.Column('modality', sa.Enum('video', 'text', 'interactive', 'project', 'audio', 'mixed', name='modality'), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.VECTOR(dim=384), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('difficulty >= 1 AND difficulty <= 5', name=op.f('ck_resources_difficulty_range')),
    sa.CheckConstraint('duration_minutes >= 0', name=op.f('ck_resources_duration_non_negative')),
    sa.CheckConstraint('rating IS NULL OR (rating >= 0 AND rating <= 5)', name=op.f('ck_resources_rating_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources')),
    sa.UniqueConstraint('provider', 'external_id', name='uq_resources_provider_external_id')
    )
    op.create_index(op.f('ix_resources_is_active'), 'resources', ['is_active'], unique=False)
    op.create_index(op.f('ix_resources_provider'), 'resources', ['provider'], unique=False)
    op.create_index('ix_resources_type_difficulty', 'resources', ['type', 'difficulty'], unique=False)
    op.create_table('skill_categories',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_categories'))
    )
    op.create_index(op.f('ix_skill_categories_slug'), 'skill_categories', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('learner', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('feedback',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('resource', 'path', 'path_item', 'recommendation', 'assessment', name='feedback_target_type'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('signal', sa.Enum('up', 'down', 'too_easy', 'too_hard', 'irrelevant', 'loved', name='feedback_signal'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name=op.f('ck_feedback_rating_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feedback_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_index('ix_feedback_target_type_target_id', 'feedback', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_table('learner_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('goal_text_raw', sa.Text(), nullable=True),
    sa.Column('experience_level', sa.Enum('beginner', 'intermediate', 'advanced', 'expert', name='experience_level'), nullable=False),
    sa.Column('weekly_hours', sa.Integer(), nullable=False),
    sa.Column('target_deadline', sa.Date(), nullable=True),
    sa.Column('preferred_modalities', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('preferred_languages', postgresql.ARRAY(sa.String(length=16)), nullable=False),
    sa.Column('learning_style', sa.String(length=64), nullable=True),
    sa.Column('budget_ceiling', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('extraction_model', sa.String(length=128), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('extraction_confidence IS NULL OR (extraction_confidence >= 0 AND extraction_confidence <= 1)', name=op.f('ck_learner_profiles_extraction_confidence_range')),
    sa.CheckConstraint('weekly_hours >= 0 AND weekly_hours <= 168', name=op.f('ck_learner_profiles_weekly_hours_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learner_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_learner_profiles_user_id'))
    )
    op.create_table('learning_goals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_input', sa.Text(), nullable=True),
    sa.Column('target_role', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'achieved', 'paused', 'abandoned', name='goal_status'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('priority >= 1 AND priority <= 5', name=op.f('ck_learning_goals_priority_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_goals'))
    )
    op.create_index(op.f('ix_learning_goals_status'), 'learning_goals', ['status'], unique=False)
    op.create_index(op.f('ix_learning_goals_user_id'), 'learning_goals', ['user_id'], unique=False)
    op.create_table('skills',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=True),
    sa.Column('level_scale', sa.Integer(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.VECTOR(dim=384), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('difficulty >= 1 AND difficulty <= 5', name=op.f('ck_skills_difficulty_range')),
    sa.ForeignKeyConstraint(['category_id'], ['skill_categories.id'], name=op.f('fk_skills_category_id_skill_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    op.create_index(op.f('ix_skills_category_id'), 'skills', ['category_id'], unique=False)
    op.create_index('ix_skills_category_id_difficulty', 'skills', ['category_id', 'difficulty'], unique=False)
    op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
    op.create_table('assessments',
    sa.Column('skill_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('diagnostic', 'checkpoint', 'final', 'practice', name='assessment_type'), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('passing_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('source_model', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('difficulty >= 1 AND difficulty <= 5', name=op.f('ck_assessments_difficulty_range')),
    sa.CheckConstraint('passing_score >= 0 AND passing_score <= 1', name=op.f('ck_assessments_passing_score_range')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_assessments_skill_id_skills'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments'))
    )
    op.create_index(op.f('ix_assessments_skill_id'), 'assessments', ['skill_id'], unique=False)
    op.create_table('learning_goal_skills',
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('required_level', sa.Float(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('importance >= 0 AND importance <= 1', name=op.f('ck_learning_goal_skills_importance_range')),
    sa.CheckConstraint('required_level >= 0 AND required_level <= 10', name=op.f('ck_learning_goal_skills_required_level_range')),
    sa.ForeignKeyConstraint(['goal_id'], ['learning_goals.id'], name=op.f('fk_learning_goal_skills_goal_id_learning_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_learning_goal_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_goal_skills')),
    sa.UniqueConstraint('goal_id', 'skill_id', name='uq_learning_goal_skills_goal_id_skill_id')
    )
    op.create_index(op.f('ix_learning_goal_skills_goal_id'), 'learning_goal_skills', ['goal_id'], unique=False)
    op.create_index(op.f('ix_learning_goal_skills_skill_id'), 'learning_goal_skills', ['skill_id'], unique=False)
    op.create_table('learning_paths',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=True),
    sa.Column('supersedes_path_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'completed', 'superseded', 'archived', name='path_status'), nullable=False),
    sa.Column('generator_version', sa.String(length=32), nullable=True),
    sa.Column('constraints_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version >= 1', name=op.f('ck_learning_paths_version_positive')),
    sa.ForeignKeyConstraint(['goal_id'], ['learning_goals.id'], name=op.f('fk_learning_paths_goal_id_learning_goals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_path_id'], ['learning_paths.id'], name=op.f('fk_learning_paths_supersedes_path_id_learning_paths'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_paths_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_paths'))
    )
    op.create_index(op.f('ix_learning_paths_goal_id'), 'learning_paths', ['goal_id'], unique=False)
    op.create_index(op.f('ix_learning_paths_user_id'), 'learning_paths', ['user_id'], unique=False)
    op.create_index('ix_learning_paths_user_id_status', 'learning_paths', ['user_id', 'status'], unique=False)
    op.create_table('prerequisites',
    sa.Column('source_skill_id', sa.UUID(), nullable=False),
    sa.Column('prerequisite_skill_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('hard_prerequisite', 'soft_prerequisite', 'recommended', 'related', name='relationship_type'), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('min_level', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('min_level >= 0 AND min_level <= 10', name=op.f('ck_prerequisites_min_level_range')),
    sa.CheckConstraint('source_skill_id <> prerequisite_skill_id', name=op.f('ck_prerequisites_no_self_prerequisite')),
    sa.CheckConstraint('strength >= 0 AND strength <= 1', name=op.f('ck_prerequisites_strength_range')),
    sa.ForeignKeyConstraint(['prerequisite_skill_id'], ['skills.id'], name=op.f('fk_prerequisites_prerequisite_skill_id_skills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_skill_id'], ['skills.id'], name=op.f('fk_prerequisites_source_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prerequisites')),
    sa.UniqueConstraint('source_skill_id', 'prerequisite_skill_id', name='uq_prerequisites_source_skill_id_prerequisite_skill_id')
    )
    op.create_index(op.f('ix_prerequisites_prerequisite_skill_id'), 'prerequisites', ['prerequisite_skill_id'], unique=False)
    op.create_index(op.f('ix_prerequisites_relationship_type'), 'prerequisites', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_prerequisites_source_skill_id'), 'prerequisites', ['source_skill_id'], unique=False)
    op.create_table('resource_skills',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('teaches_level_from', sa.Float(), nullable=False),
    sa.Column('teaches_level_to', sa.Float(), nullable=False),
    sa.Column('coverage_weight', sa.Float(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('coverage_weight >= 0 AND coverage_weight <= 1', name=op.f('ck_resource_skills_coverage_weight_range')),
    sa.CheckConstraint('teaches_level_to > teaches_level_from', name=op.f('ck_resource_skills_teaches_level_band_ordered')),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_skills_resource_id_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_resource_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_skills')),
    sa.UniqueConstraint('resource_id', 'skill_id', name='uq_resource_skills_resource_id_skill_id')
    )
    op.create_index(op.f('ix_resource_skills_resource_id'), 'resource_skills', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_skills_skill_id'), 'resource_skills', ['skill_id'], unique=False)
    op.create_table('user_skills',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('current_level', sa.Float(), nullable=False),
    sa.Column('target_level', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_source', sa.Enum('self_report', 'assessment', 'completion', 'inferred', name='evidence_source'), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_user_skills_confidence_range')),
    sa.CheckConstraint('current_level >= 0 AND current_level <= 10', name=op.f('ck_user_skills_current_level_range')),
    sa.CheckConstraint('target_level IS NULL OR (target_level >= 0 AND target_level <= 10)', name=op.f('ck_user_skills_target_level_range')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_user_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_skills_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_skills')),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_user_skills_user_id_skill_id')
    )
    op.create_index(op.f('ix_user_skills_skill_id'), 'user_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_user_skills_user_id'), 'user_skills', ['user_id'], unique=False)
    op.create_table('assessment_questions',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Enum('single_choice', 'multiple_choice', 'true_false', 'short_answer', name='question_type'), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('difficulty_b', sa.Float(), nullable=False),
    sa.Column('discrimination_a', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('points > 0', name=op.f('ck_assessment_questions_points_positive')),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_questions_assessment_id_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_assessment_questions_skill_id_skills'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_questions')),
    sa.UniqueConstraint('assessment_id', 'order_index', name='uq_assessment_questions_assessment_id_order_index')
    )
    op.create_index(op.f('ix_assessment_questions_assessment_id'), 'assessment_questions', ['assessment_id'], unique=False)
    op.create_table('learning_path_items',
    sa.Column('path_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('milestone_index', sa.Integer(), nullable=False),
    sa.Column('milestone_title', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('item_type', sa.Enum('resource', 'assessment', 'milestone_review', name='path_item_type'), nullable=False),
    sa.Column('status', sa.Enum('locked', 'available', 'in_progress', 'completed', 'skipped', name='path_item_status'), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rationale_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_end', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('order_index >= 0', name=op.f('ck_learning_path_items_order_index_non_negative')),
    sa.CheckConstraint('resource_id IS NOT NULL OR assessment_id IS NOT NULL', name=op.f('ck_learning_path_items_item_targets_resource_or_assessment')),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_learning_path_items_assessment_id_assessments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.id'], name=op.f('fk_learning_path_items_path_id_learning_paths'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_learning_path_items_resource_id_resources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_path_items')),
    sa.UniqueConstraint('path_id', 'order_index', name='uq_learning_path_items_path_id_order_index')
    )
    op.create_index(op.f('ix_learning_path_items_assessment_id'), 'learning_path_items', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_learning_path_items_path_id'), 'learning_path_items', ['path_id'], unique=False)
    op.create_index('ix_learning_path_items_path_id_milestone_index', 'learning_path_items', ['path_id', 'milestone_index'], unique=False)
    op.create_index(op.f('ix_learning_path_items_resource_id'), 'learning_path_items', ['resource_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=True),
    sa.Column('path_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'dismissed', 'expired', name='recommendation_status'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('rationale_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rank >= 0', name=op.f('ck_recommendations_rank_non_negative')),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.id'], name=op.f('fk_recommendations_path_id_learning_paths'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_recommendations_resource_id_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_recommendations_skill_id_skills'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_resource_id'), 'recommendations', ['resource_id'], unique=False)
    op.create_index(op.f('ix_recommendations_skill_id'), 'recommendations', ['skill_id'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_index('ix_recommendations_user_id_status', 'recommendations', ['user_id', 'status'], unique=False)
    op.create_table('assessment_results',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('path_item_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('theta_estimate', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('responses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 0', name=op.f('ck_assessment_results_score_non_negative')),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_results_assessment_id_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_item_id'], ['learning_path_items.id'], name=op.f('fk_assessment_results_path_item_id_learning_path_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assessment_results_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_results'))
    )
    op.create_index(op.f('ix_assessment_results_assessment_id'), 'assessment_results', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_results_user_id'), 'assessment_results', ['user_id'], unique=False)
    op.create_index('ix_assessment_results_user_id_assessment_id', 'assessment_results', ['user_id', 'assessment_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('path_item_id', sa.UUID(), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('started', 'progressed', 'completed', 'skipped', 'abandoned', name='progress_event_type'), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('progress_pct >= 0 AND progress_pct <= 100', name=op.f('ck_user_progress_progress_pct_range')),
    sa.CheckConstraint('time_spent_minutes >= 0', name=op.f('ck_user_progress_time_spent_non_negative')),
    sa.ForeignKeyConstraint(['path_item_id'], ['learning_path_items.id'], name=op.f('fk_user_progress_path_item_id_learning_path_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_user_progress_resource_id_resources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_progress'))
    )
    op.create_index(op.f('ix_user_progress_path_item_id'), 'user_progress', ['path_item_id'], unique=False)
    op.create_index(op.f('ix_user_progress_resource_id'), 'user_progress', ['resource_id'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_index('ix_user_progress_user_id_occurred_at', 'user_progress', ['user_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_progress_user_id_occurred_at', table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_resource_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_path_item_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index('ix_assessment_results_user_id_assessment_id', table_name='assessment_results')
    op.drop_index(op.f('ix_assessment_results_user_id'), table_name='assessment_results')
    op.drop_index(op.f('ix_assessment_results_assessment_id'), table_name='assessment_results')
    op.drop_table('assessment_results')
    op.drop_index('ix_recommendations_user_id_status', table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_skill_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_resource_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_learning_path_items_resource_id'), table_name='learning_path_items')
    op.drop_index('ix_learning_path_items_path_id_milestone_index', table_name='learning_path_items')
    op.drop_index(op.f('ix_learning_path_items_path_id'), table_name='learning_path_items')
    op.drop_index(op.f('ix_learning_path_items_assessment_id'), table_name='learning_path_items')
    op.drop_table('learning_path_items')
    op.drop_index(op.f('ix_assessment_questions_assessment_id'), table_name='assessment_questions')
    op.drop_table('assessment_questions')
    op.drop_index(op.f('ix_user_skills_user_id'), table_name='user_skills')
    op.drop_index(op.f('ix_user_skills_skill_id'), table_name='user_skills')
    op.drop_table('user_skills')
    op.drop_index(op.f('ix_resource_skills_skill_id'), table_name='resource_skills')
    op.drop_index(op.f('ix_resource_skills_resource_id'), table_name='resource_skills')
    op.drop_table('resource_skills')
    op.drop_index(op.f('ix_prerequisites_source_skill_id'), table_name='prerequisites')
    op.drop_index(op.f('ix_prerequisites_relationship_type'), table_name='prerequisites')
    op.drop_index(op.f('ix_prerequisites_prerequisite_skill_id'), table_name='prerequisites')
    op.drop_table('prerequisites')
    op.drop_index('ix_learning_paths_user_id_status', table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_user_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_goal_id'), table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_index(op.f('ix_learning_goal_skills_skill_id'), table_name='learning_goal_skills')
    op.drop_index(op.f('ix_learning_goal_skills_goal_id'), table_name='learning_goal_skills')
    op.drop_table('learning_goal_skills')
    op.drop_index(op.f('ix_assessments_skill_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_skills_slug'), table_name='skills')
    op.drop_index('ix_skills_category_id_difficulty', table_name='skills')
    op.drop_index(op.f('ix_skills_category_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_learning_goals_user_id'), table_name='learning_goals')
    op.drop_index(op.f('ix_learning_goals_status'), table_name='learning_goals')
    op.drop_table('learning_goals')
    op.drop_table('learner_profiles')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index('ix_feedback_target_type_target_id', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skill_categories_slug'), table_name='skill_categories')
    op.drop_table('skill_categories')
    op.drop_index('ix_resources_type_difficulty', table_name='resources')
    op.drop_index(op.f('ix_resources_provider'), table_name='resources')
    op.drop_index(op.f('ix_resources_is_active'), table_name='resources')
    op.drop_table('resources')

    # drop_table() leaves the native enum types behind, which would make a
    # subsequent upgrade fail with DuplicateObjectError. Drop them explicitly.
    for enum_name in (
        "assessment_type",
        "evidence_source",
        "experience_level",
        "feedback_signal",
        "feedback_target_type",
        "goal_status",
        "modality",
        "path_item_status",
        "path_item_type",
        "path_status",
        "progress_event_type",
        "question_type",
        "recommendation_status",
        "relationship_type",
        "resource_type",
        "user_role",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
