"""learner profile engine fields

Revision ID: 9d909cd90180
Revises: 6b23d77231f9
Create Date: 2026-08-18 22:58:21.294555
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '9d909cd90180'
down_revision: str | None = '6b23d77231f9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("learner_profiles", sa.Column("target_role", sa.String(length=255), nullable=True))
    op.add_column(
        "learner_profiles",
        sa.Column(
            "interests",
            postgresql.ARRAY(sa.String(length=64)),
            nullable=False,
            server_default="{}",
        ),
    )
    op.add_column(
        "learner_profiles",
        sa.Column(
            "completed_courses",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
    )
    op.add_column(
        "learner_profiles",
        sa.Column(
            "completed_projects",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
    )
    op.add_column(
        "learner_profiles",
        sa.Column(
            "learning_preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="{}",
        ),
    )
    op.add_column(
        "user_skills",
        sa.Column("proficiency", sa.Float(), nullable=False, server_default="0"),
    )

    # Backfill proficiency from any pre-existing current_level (0..10 -> 0..1),
    # then drop the transient server defaults so the application layer owns them.
    op.execute(
        "UPDATE user_skills us SET proficiency = LEAST(1.0, GREATEST(0.0, "
        "us.current_level / NULLIF(s.level_scale, 0))) "
        "FROM skills s WHERE s.id = us.skill_id"
    )
    for table, column in (
        ("learner_profiles", "interests"),
        ("learner_profiles", "completed_courses"),
        ("learner_profiles", "completed_projects"),
        ("learner_profiles", "learning_preferences"),
        ("user_skills", "proficiency"),
    ):
        op.alter_column(table, column, server_default=None)
    op.create_check_constraint(
        "proficiency_range", "user_skills", "proficiency >= 0 AND proficiency <= 1"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("proficiency_range", "user_skills", type_="check")
    op.drop_column("user_skills", "proficiency")
    op.drop_column('learner_profiles', 'learning_preferences')
    op.drop_column('learner_profiles', 'completed_projects')
    op.drop_column('learner_profiles', 'completed_courses')
    op.drop_column('learner_profiles', 'interests')
    op.drop_column('learner_profiles', 'target_role')
    # ### end Alembic commands ###
