"""Declarative seed data for the learning-resource catalogue.

Pure data — no I/O. `seed.py` upserts these. Resources reference skills by
slug (resolved to ids by the loader), so the catalogue stays decoupled from
skill uuids.

The video catalogue is REAL: every title, channel, runtime and id below was
read from YouTube's oEmbed endpoint and watch page rather than written by
hand, so `estimated_hours` is the actual runtime and the URL resolves. Any
candidate that failed verification was dropped rather than guessed at.
Regenerate with `scripts/refresh_catalogue.py`.

Projects and assessments are completed INSIDE the app, so they point at the
dashboard rather than an external page.

difficulty: 1..5. `teaches` bands and prerequisite `min_proficiency` are on
the same 0..1 proficiency scale the learner profile uses.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class TeachSeed:
    skill: str  # skill slug
    level_from: float = 0.0
    level_to: float = 0.6
    is_primary: bool = False


@dataclass(frozen=True)
class ResourceSeed:
    external_id: str
    title: str
    resource_type: str
    provider: str
    url: str
    difficulty: int
    estimated_hours: float
    description: str
    teaches: tuple[TeachSeed, ...]
    prerequisites: tuple[tuple[str, float], ...] = ()
    quality_score: float | None = None
    rating: float | None = None
    rating_count: int = 0
    modality: str = "mixed"
    metadata: dict = field(default_factory=dict)


def _t(skill: str, lo: float = 0.0, hi: float = 0.6, primary: bool = True) -> TeachSeed:
    return TeachSeed(skill=skill, level_from=lo, level_to=hi, is_primary=primary)


#: Watched on YouTube; `external_id` is the video id.
_YT = "https://www.youtube.com/watch?v="

RESOURCES: tuple[ResourceSeed, ...] = (
    # ---------------------------------------------------- video catalogue
    ResourceSeed(
        "rfscVS0vtbw", "Learn Python - Full Course for Beginners [Tutorial]",
        "course", "freeCodeCamp.org", _YT + "rfscVS0vtbw",
        1, 4.45,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("python", 0.0, 0.55), _t("programming-fundamentals", 0.0, 0.4, False),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "_uQrJ0TkZlc", "Python Full Course for Beginners",
        "course", "Programming with Mosh", _YT + "_uQrJ0TkZlc",
        1, 6.24,
        "Course by Programming with Mosh on YouTube.",
        (_t("python", 0.0, 0.55),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "kqtD5dpn9C8", "Python for Beginners - Learn Coding with Python in 1 Hour",
        "video", "Programming with Mosh", _YT + "kqtD5dpn9C8",
        1, 1.0,
        "Video by Programming with Mosh on YouTube.",
        (_t("programming-fundamentals", 0.0, 0.55), _t("python", 0.0, 0.4, False),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "5NgNicANyqM", "Harvard CS50’s Artificial Intelligence with Python – Full University Course",
        "course", "freeCodeCamp.org", _YT + "5NgNicANyqM",
        3, 11.86,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("programming-fundamentals", 0.2, 0.75), _t("machine-learning", 0.2, 0.6, False),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "RBSGKlAvoiM", "Data Structures Easy to Advanced Course - Full Tutorial from a Google Engineer",
        "course", "freeCodeCamp.org", _YT + "RBSGKlAvoiM",
        3, 8.05,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("data-structures-algorithms", 0.2, 0.75),),
        (("programming-fundamentals", 0.35), ("python", 0.35),),
        modality="video",
    ),
    ResourceSeed(
        "8hly31xKli0", "Algorithms and Data Structures Tutorial - Full Course for Beginners",
        "course", "freeCodeCamp.org", _YT + "8hly31xKli0",
        2, 5.37,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("data-structures-algorithms", 0.0, 0.65),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "HXV3zeQKqGY", "SQL Tutorial - Full Database Course for Beginners",
        "course", "freeCodeCamp.org", _YT + "HXV3zeQKqGY",
        2, 4.34,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("sql", 0.0, 0.65),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "RGOj5yH7evk", "Git and GitHub for Beginners - Crash Course",
        "course", "freeCodeCamp.org", _YT + "RGOj5yH7evk",
        1, 1.14,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("version-control-git", 0.0, 0.55),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "fNk_zzaMoSs", "Vectors | Chapter 1, Essence of linear algebra",
        "video", "3Blue1Brown", _YT + "fNk_zzaMoSs",
        3, 0.16,
        "Video by 3Blue1Brown on YouTube.",
        (_t("linear-algebra", 0.2, 0.75),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "WUvTyaaNkzM", "The essence of calculus",
        "video", "3Blue1Brown", _YT + "WUvTyaaNkzM",
        3, 0.28,
        "Video by 3Blue1Brown on YouTube.",
        (_t("calculus", 0.2, 0.75),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "IHZwWFHWa-w", "Gradient descent, how neural networks learn | Deep Learning Chapter 2",
        "video", "3Blue1Brown", _YT + "IHZwWFHWa-w",
        4, 0.34,
        "Video by 3Blue1Brown on YouTube.",
        (_t("optimization", 0.4, 0.85), _t("neural-networks", 0.4, 0.7, False),),
        (("calculus", 0.45), ("linear-algebra", 0.45),),
        modality="video",
    ),
    ResourceSeed(
        "Ilg3gGewQ5U", "Backpropagation, intuitively | Deep Learning Chapter 3",
        "video", "3Blue1Brown", _YT + "Ilg3gGewQ5U",
        4, 0.21,
        "Video by 3Blue1Brown on YouTube.",
        (_t("optimization", 0.4, 0.85), _t("neural-networks", 0.4, 0.7, False), _t("deep-learning", 0.4, 0.7, False),),
        (("calculus", 0.45), ("linear-algebra", 0.45),),
        modality="video",
    ),
    ResourceSeed(
        "qBigTkBLU6g", "StatQuest: Histograms, Clearly Explained",
        "video", "StatQuest with Josh Starmer", _YT + "qBigTkBLU6g",
        2, 0.06,
        "Video by StatQuest with Josh Starmer on YouTube.",
        (_t("probability", 0.0, 0.65), _t("statistics", 0.0, 0.5, False),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "xxpc-HPKN28", "Statistics - A Full University Course on Data Science Basics",
        "course", "freeCodeCamp.org", _YT + "xxpc-HPKN28",
        3, 8.25,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("statistics", 0.2, 0.75), _t("probability", 0.2, 0.6, False),),
        (("probability", 0.35),),
        modality="video",
    ),
    ResourceSeed(
        "Gv9_4yMHFhI", "A Gentle Introduction to Machine Learning",
        "video", "StatQuest with Josh Starmer", _YT + "Gv9_4yMHFhI",
        2, 0.21,
        "Video by StatQuest with Josh Starmer on YouTube.",
        (_t("machine-learning", 0.0, 0.65),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "ZyhVh-qRZPA", "Python Pandas Tutorial (Part 1): Getting Started with Data Analysis - Installation and Loading Data",
        "video", "Corey Schafer", _YT + "ZyhVh-qRZPA",
        2, 0.38,
        "Video by Corey Schafer on YouTube.",
        (_t("data-wrangling", 0.0, 0.65), _t("python", 0.0, 0.5, False),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "vmEHCJofslg", "Complete Python Pandas Data Science Tutorial! (Reading CSV/Excel files, Sorting, Filtering, Groupby)",
        "course", "Keith Galli", _YT + "vmEHCJofslg",
        2, 1.01,
        "Course by Keith Galli on YouTube.",
        (_t("data-wrangling", 0.0, 0.65), _t("python", 0.0, 0.5, False),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "QUT1VHiLmmI", "Python NumPy Tutorial for Beginners",
        "course", "freeCodeCamp.org", _YT + "QUT1VHiLmmI",
        2, 0.97,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("data-wrangling", 0.0, 0.65), _t("linear-algebra", 0.0, 0.5, False),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "UO98lJQ3QGI", "Matplotlib Tutorial (Part 1): Creating and Customizing Our First Plots",
        "video", "Corey Schafer", _YT + "UO98lJQ3QGI",
        2, 0.58,
        "Video by Corey Schafer on YouTube.",
        (_t("data-visualization", 0.0, 0.65), _t("python", 0.0, 0.5, False),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "hSPmj7mK6ng", "Introduction to Dash Plotly - Data Visualization in Python",
        "video", "Charming Data", _YT + "hSPmj7mK6ng",
        2, 0.49,
        "Video by Charming Data on YouTube.",
        (_t("data-visualization", 0.0, 0.65), _t("python", 0.0, 0.5, False),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "q8q3OFFfY6c", "Twitter Data Pipeline using Airflow for Beginners | Data Engineering Project",
        "video", "Darshil Parmar", _YT + "q8q3OFFfY6c",
        3, 0.67,
        "Video by Darshil Parmar on YouTube.",
        (_t("etl-pipelines", 0.2, 0.75), _t("python", 0.2, 0.6, False),),
        (("python", 0.35), ("sql", 0.35),),
        modality="video",
    ),
    ResourceSeed(
        "_C8kWso4ne4", "PySpark Tutorial",
        "course", "freeCodeCamp.org", _YT + "_C8kWso4ne4",
        4, 1.82,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("big-data-spark", 0.4, 0.85), _t("etl-pipelines", 0.4, 0.7, False),),
        (("etl-pipelines", 0.45),),
        modality="video",
    ),
    ResourceSeed(
        "P8ERBy91Y90", "How is data prepared for machine learning?",
        "video", "AltexSoft", _YT + "P8ERBy91Y90",
        3, 0.23,
        "Video by AltexSoft on YouTube.",
        (_t("feature-engineering", 0.2, 0.75), _t("data-wrangling", 0.2, 0.6, False),),
        (("data-wrangling", 0.35),),
        modality="video",
    ),
    ResourceSeed(
        "ua-CiDNNj30", "Learn Data Science Tutorial - Full Course for Beginners",
        "course", "freeCodeCamp.org", _YT + "ua-CiDNNj30",
        2, 5.87,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("machine-learning", 0.0, 0.65), _t("statistics", 0.0, 0.5, False), _t("data-wrangling", 0.0, 0.5, False),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "i_LwzRVP7bg", "Machine Learning for Everybody – Full Course",
        "course", "freeCodeCamp.org", _YT + "i_LwzRVP7bg",
        2, 3.9,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("machine-learning", 0.0, 0.65), _t("supervised-learning", 0.0, 0.5, False),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "pqNCD_5r0IU", "Scikit-Learn Course - Machine Learning in Python Tutorial",
        "course", "freeCodeCamp.org", _YT + "pqNCD_5r0IU",
        3, 2.91,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("supervised-learning", 0.2, 0.75), _t("machine-learning", 0.2, 0.6, False),),
        (("machine-learning", 0.35),),
        modality="video",
    ),
    ResourceSeed(
        "4qVRBYAdLAo", "Supervised Learning: Crash Course AI #2",
        "video", "CrashCourse", _YT + "4qVRBYAdLAo",
        1, 0.26,
        "Video by CrashCourse on YouTube.",
        (_t("supervised-learning", 0.0, 0.55),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "NxEHSAfFlK8", "How to implement Decision Trees from scratch with Python",
        "video", "AssemblyAI", _YT + "NxEHSAfFlK8",
        3, 0.62,
        "Video by AssemblyAI on YouTube.",
        (_t("supervised-learning", 0.2, 0.75), _t("python", 0.2, 0.6, False),),
        (("machine-learning", 0.35),),
        modality="video",
    ),
    ResourceSeed(
        "4b5d3muPQmA", "StatQuest: K-means clustering",
        "video", "StatQuest with Josh Starmer", _YT + "4b5d3muPQmA",
        3, 0.14,
        "Video by StatQuest with Josh Starmer on YouTube.",
        (_t("unsupervised-learning", 0.2, 0.75),),
        (("machine-learning", 0.35),),
        modality="video",
    ),
    ResourceSeed(
        "4jRBRDbJemM", "ROC and AUC, Clearly Explained!",
        "video", "StatQuest with Josh Starmer", _YT + "4jRBRDbJemM",
        3, 0.27,
        "Video by StatQuest with Josh Starmer on YouTube.",
        (_t("model-evaluation", 0.2, 0.75),),
        (("machine-learning", 0.35),),
        modality="video",
    ),
    ResourceSeed(
        "J4Wdy0Wc_xQ", "StatQuest: Random Forests Part 1 - Building, Using and Evaluating",
        "video", "StatQuest with Josh Starmer", _YT + "J4Wdy0Wc_xQ",
        4, 0.17,
        "Video by StatQuest with Josh Starmer on YouTube.",
        (_t("ensemble-methods", 0.4, 0.85), _t("supervised-learning", 0.4, 0.7, False),),
        (("supervised-learning", 0.45),),
        modality="video",
    ),
    ResourceSeed(
        "ok2s1vV9XW0", "Machine Learning Tutorial Python - 11  Random Forest",
        "video", "codebasics", _YT + "ok2s1vV9XW0",
        3, 0.21,
        "Video by codebasics on YouTube.",
        (_t("ensemble-methods", 0.2, 0.75), _t("python", 0.2, 0.6, False),),
        (("supervised-learning", 0.35),),
        modality="video",
    ),
    ResourceSeed(
        "efR1C6CvhmE", "Support Vector Machines Part 1 (of 3): Main Ideas!!!",
        "video", "StatQuest with Josh Starmer", _YT + "efR1C6CvhmE",
        4, 0.34,
        "Video by StatQuest with Josh Starmer on YouTube.",
        (_t("supervised-learning", 0.4, 0.85), _t("model-evaluation", 0.4, 0.7, False),),
        (("machine-learning", 0.45),),
        modality="video",
    ),
    ResourceSeed(
        "aircAruvnKk", "But what is a neural network? | Deep learning chapter 1",
        "video", "3Blue1Brown", _YT + "aircAruvnKk",
        3, 0.31,
        "Video by 3Blue1Brown on YouTube.",
        (_t("neural-networks", 0.2, 0.75),),
        (("linear-algebra", 0.35), ("machine-learning", 0.35),),
        modality="video",
    ),
    ResourceSeed(
        "dPWYUELwIdM", "How Deep Neural Networks Work - Full Course for Beginners",
        "course", "freeCodeCamp.org", _YT + "dPWYUELwIdM",
        3, 3.85,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("neural-networks", 0.2, 0.75), _t("deep-learning", 0.2, 0.6, False),),
        (("linear-algebra", 0.35), ("machine-learning", 0.35),),
        modality="video",
    ),
    ResourceSeed(
        "VMj-3S1tku0", "The spelled-out intro to neural networks and backpropagation: building micrograd",
        "course", "Andrej Karpathy", _YT + "VMj-3S1tku0",
        4, 2.43,
        "Course by Andrej Karpathy on YouTube.",
        (_t("neural-networks", 0.4, 0.85), _t("deep-learning", 0.4, 0.7, False), _t("python", 0.4, 0.7, False),),
        (("linear-algebra", 0.45), ("machine-learning", 0.45),),
        modality="video",
    ),
    ResourceSeed(
        "bte8Er0QhDg", "Neural Network Python Project - Handwritten Digit Recognition",
        "video", "NeuralNine", _YT + "bte8Er0QhDg",
        3, 0.38,
        "Video by NeuralNine on YouTube.",
        (_t("neural-networks", 0.2, 0.75), _t("python", 0.2, 0.6, False),),
        (("linear-algebra", 0.35), ("machine-learning", 0.35),),
        modality="video",
    ),
    ResourceSeed(
        "V_xro1bcAuA", "PyTorch for Deep Learning & Machine Learning – Full Course",
        "course", "freeCodeCamp.org", _YT + "V_xro1bcAuA",
        3, 25.62,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("pytorch", 0.2, 0.75), _t("deep-learning", 0.2, 0.6, False),),
        (("python", 0.35),),
        modality="video",
    ),
    ResourceSeed(
        "Z_ikDlimN6A", "Learn PyTorch for deep learning in a day. Literally.",
        "course", "Daniel Bourke", _YT + "Z_ikDlimN6A",
        3, 25.62,
        "Course by Daniel Bourke on YouTube.",
        (_t("pytorch", 0.2, 0.75), _t("deep-learning", 0.2, 0.6, False),),
        (("python", 0.35),),
        modality="video",
    ),
    ResourceSeed(
        "tPYj3fFJGjk", "TensorFlow 2.0 Complete Course - Python Neural Networks for Beginners Tutorial",
        "course", "freeCodeCamp.org", _YT + "tPYj3fFJGjk",
        3, 6.87,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("deep-learning", 0.2, 0.75), _t("neural-networks", 0.2, 0.6, False),),
        (("neural-networks", 0.35),),
        modality="video",
    ),
    ResourceSeed(
        "WFr2WgN9_xE", "Python Machine Learning & AI Mega Course - Learn 4 Different Areas of ML & AI",
        "course", "Tech With Tim", _YT + "WFr2WgN9_xE",
        3, 7.57,
        "Course by Tech With Tim on YouTube.",
        (_t("deep-learning", 0.2, 0.75), _t("python", 0.2, 0.6, False), _t("machine-learning", 0.2, 0.6, False),),
        (("neural-networks", 0.35),),
        modality="video",
    ),
    ResourceSeed(
        "oXlwWbU8l2o", "OpenCV Course - Full Tutorial with Python",
        "course", "freeCodeCamp.org", _YT + "oXlwWbU8l2o",
        2, 3.69,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("image-processing", 0.0, 0.65), _t("python", 0.0, 0.5, False),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "YCzL96nL7j0", "Long Short-Term Memory (LSTM), Clearly Explained",
        "video", "StatQuest with Josh Starmer", _YT + "YCzL96nL7j0",
        4, 0.35,
        "Video by StatQuest with Josh Starmer on YouTube.",
        (_t("rnn", 0.4, 0.85), _t("deep-learning", 0.4, 0.7, False),),
        (("deep-learning", 0.45),),
        modality="video",
    ),
    ResourceSeed(
        "4Bdc55j80l8", "Illustrated Guide to Transformers Neural Network: A step by step explanation",
        "video", "The AI Hacker", _YT + "4Bdc55j80l8",
        4, 0.25,
        "Video by The AI Hacker on YouTube.",
        (_t("transformers", 0.4, 0.85), _t("deep-learning", 0.4, 0.7, False),),
        (("deep-learning", 0.45),),
        modality="video",
    ),
    ResourceSeed(
        "zxQyTK8quyY", "Transformer Neural Networks, ChatGPT's foundation, Clearly Explained!!!",
        "video", "StatQuest with Josh Starmer", _YT + "zxQyTK8quyY",
        5, 0.6,
        "Video by StatQuest with Josh Starmer on YouTube.",
        (_t("transformers", 0.55, 0.95), _t("rnn", 0.55, 0.8, False),),
        (("deep-learning", 0.55),),
        modality="video",
    ),
    ResourceSeed(
        "dIUTsFT2MeQ", "Natural Language Processing with spaCy & Python - Course for Beginners",
        "course", "freeCodeCamp.org", _YT + "dIUTsFT2MeQ",
        3, 3.04,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("nlp-fundamentals", 0.2, 0.75), _t("python", 0.2, 0.6, False),),
        (("machine-learning", 0.35), ("python", 0.35),),
        modality="video",
    ),
    ResourceSeed(
        "viZrOnJclY0", "Word Embedding and Word2Vec, Clearly Explained!!!",
        "video", "StatQuest with Josh Starmer", _YT + "viZrOnJclY0",
        3, 0.27,
        "Video by StatQuest with Josh Starmer on YouTube.",
        (_t("word-embeddings", 0.2, 0.75), _t("nlp-fundamentals", 0.2, 0.6, False),),
        (("nlp-fundamentals", 0.35),),
        modality="video",
    ),
    ResourceSeed(
        "kCc8FmEb1nY", "Let's build GPT: from scratch, in code, spelled out.",
        "course", "Andrej Karpathy", _YT + "kCc8FmEb1nY",
        5, 1.94,
        "Course by Andrej Karpathy on YouTube.",
        (_t("language-models", 0.55, 0.95), _t("transformers", 0.55, 0.8, False), _t("pytorch", 0.55, 0.8, False),),
        (("nlp-fundamentals", 0.55), ("transformers", 0.55),),
        modality="video",
    ),
    ResourceSeed(
        "PaCmpygFfXo", "The spelled-out intro to language modeling: building makemore",
        "course", "Andrej Karpathy", _YT + "PaCmpygFfXo",
        5, 1.96,
        "Course by Andrej Karpathy on YouTube.",
        (_t("language-models", 0.55, 0.95), _t("neural-networks", 0.55, 0.8, False),),
        (("nlp-fundamentals", 0.55), ("transformers", 0.55),),
        modality="video",
    ),
    ResourceSeed(
        "LPZh9BOjkQs", "Large Language Models explained briefly",
        "video", "3Blue1Brown", _YT + "LPZh9BOjkQs",
        2, 0.13,
        "Video by 3Blue1Brown on YouTube.",
        (_t("large-language-models", 0.0, 0.65),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "zizonToFXDs", "Introduction to large language models",
        "video", "Google Cloud Tech", _YT + "zizonToFXDs",
        2, 0.26,
        "Video by Google Cloud Tech on YouTube.",
        (_t("large-language-models", 0.0, 0.65), _t("generative-ai", 0.0, 0.5, False),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "p3sij8QzONQ", "LLMs from Scratch – Practical Engineering from Base Model to PPO RLHF",
        "course", "freeCodeCamp.org", _YT + "p3sij8QzONQ",
        5, 6.11,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("fine-tuning-llms", 0.55, 0.95), _t("large-language-models", 0.55, 0.8, False),),
        (("large-language-models", 0.55),),
        modality="video",
    ),
    ResourceSeed(
        "T-D1OfcDW1M", "What is Retrieval-Augmented Generation (RAG)?",
        "video", "IBM Technology", _YT + "T-D1OfcDW1M",
        3, 0.11,
        "Video by IBM Technology on YouTube.",
        (_t("rag-systems", 0.2, 0.75), _t("large-language-models", 0.2, 0.6, False),),
        (("large-language-models", 0.35),),
        modality="video",
    ),
    ResourceSeed(
        "JEBDfGqrAUA", "Vector Search RAG Tutorial – Combine Your Data with LLMs with Advanced Search",
        "course", "freeCodeCamp.org", _YT + "JEBDfGqrAUA",
        4, 1.2,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("rag-systems", 0.4, 0.85), _t("large-language-models", 0.4, 0.7, False),),
        (("large-language-models", 0.45),),
        modality="video",
    ),
    ResourceSeed(
        "yfHHvmaMkcA", "Vector Embeddings Tutorial – Code Your Own AI Assistant with GPT-4 API + LangChain + NLP",
        "course", "freeCodeCamp.org", _YT + "yfHHvmaMkcA",
        4, 0.61,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("rag-systems", 0.4, 0.85), _t("word-embeddings", 0.4, 0.7, False),),
        (("large-language-models", 0.45),),
        modality="video",
    ),
    ResourceSeed(
        "fqMOX6JJhGo", "Docker Tutorial for Beginners - A Full DevOps Course on How to Run Applications in Containers",
        "course", "freeCodeCamp.org", _YT + "fqMOX6JJhGo",
        2, 2.17,
        "Course by freeCodeCamp.org on YouTube.",
        (_t("docker-containers", 0.0, 0.65),),
        (),
        modality="video",
    ),
    ResourceSeed(
        "X48VuDVv0do", "Kubernetes Tutorial for Beginners [FULL COURSE in 4 Hours]",
        "course", "TechWorld with Nana", _YT + "X48VuDVv0do",
        4, 3.62,
        "Course by TechWorld with Nana on YouTube.",
        (_t("model-deployment", 0.4, 0.85), _t("docker-containers", 0.4, 0.7, False),),
        (("docker-containers", 0.45), ("mlops-fundamentals", 0.45),),
        modality="video",
    ),
    # ------------------------------------- projects & checkpoints (in-app)
    ResourceSeed(
        "py-project-cli", "Build a Command-Line To-Do App",
        "project", "Pathwise", "/dashboard#roadmap",
        2, 6.0,
        "Apply core Python by building a persistent CLI to-do application.",
        (_t("python", 0.4, 0.8, True),),
        (("python", 0.3),), 0.8,
        modality="project",
    ),
    ResourceSeed(
        "py-assessment-core", "Python Fundamentals Assessment",
        "assessment", "Pathwise", "/dashboard#roadmap",
        2, 1.0,
        "Diagnostic quiz covering data types, control flow and functions.",
        (_t("python", 0.0, 0.7, True),),
        (), 0.85,
        modality="interactive",
    ),
    ResourceSeed(
        "stats-project-ab", "Run an A/B Test End to End",
        "project", "Pathwise", "/dashboard#roadmap",
        3, 8.0,
        "Design, run and analyse an A/B test on a sample dataset.",
        (_t("statistics", 0.5, 0.85, True),),
        (("statistics", 0.4),), 0.79,
        modality="project",
    ),
    ResourceSeed(
        "ml-project-churn", "Predict Customer Churn",
        "project", "Pathwise", "/dashboard#roadmap",
        3, 12.0,
        "Build, evaluate and tune a churn-prediction classifier.",
        (_t("machine-learning", 0.5, 0.8, True), _t("model-evaluation", 0.4, 0.7, False),),
        (("machine-learning", 0.4),), 0.82,
        modality="project",
    ),
    ResourceSeed(
        "ml-assessment", "Machine Learning Concepts Assessment",
        "assessment", "Pathwise", "/dashboard#roadmap",
        3, 1.5,
        "Checkpoint on bias-variance, metrics and core algorithms.",
        (_t("machine-learning", 0.0, 0.8, True),),
        (("machine-learning", 0.3),), 0.86,
        modality="interactive",
    ),
    ResourceSeed(
        "pytorch-project-classifier", "Train an Image Classifier in PyTorch",
        "project", "Pathwise", "/dashboard#roadmap",
        4, 10.0,
        "Build and train a CNN image classifier from scratch in PyTorch.",
        (_t("pytorch", 0.4, 0.8, True), _t("cnn", 0.3, 0.6, False),),
        (("pytorch", 0.3), ("deep-learning", 0.4),), 0.83,
        modality="project",
    ),
    ResourceSeed(
        "cv-project-detection", "Object Detection with YOLO",
        "project", "Pathwise", "/dashboard#roadmap",
        5, 14.0,
        "Fine-tune a YOLO model for a custom object-detection task.",
        (_t("object-detection", 0.4, 0.8, True), _t("computer-vision", 0.5, 0.8, False),),
        (("computer-vision", 0.5),), 0.81,
        modality="project",
    ),
    ResourceSeed(
        "nlp-project-sentiment", "Build a Sentiment Analyzer",
        "project", "Pathwise", "/dashboard#roadmap",
        3, 8.0,
        "Train and deploy a text-sentiment classifier.",
        (_t("nlp-fundamentals", 0.4, 0.75, True),),
        (("nlp-fundamentals", 0.4),), 0.78,
        modality="project",
    ),
    ResourceSeed(
        "llm-project-rag", "Build a Retrieval-Augmented Chatbot",
        "project", "Pathwise", "/dashboard#roadmap",
        5, 16.0,
        "Ground an LLM on your own documents with a RAG pipeline.",
        (_t("rag-systems", 0.4, 0.85, True), _t("large-language-models", 0.5, 0.8, False),),
        (("large-language-models", 0.5),), 0.84,
        modality="project",
    ),
    ResourceSeed(
        "llm-assessment", "LLM Fundamentals Assessment",
        "assessment", "Pathwise", "/dashboard#roadmap",
        4, 1.0,
        "Checkpoint on tokenization, prompting, context windows and evaluation.",
        (_t("large-language-models", 0.0, 0.8, True),),
        (("large-language-models", 0.3),), 0.85,
        modality="interactive",
    ),
    ResourceSeed(
        "mlops-project-deploy", "Deploy and Monitor a Model API",
        "project", "Pathwise", "/dashboard#roadmap",
        4, 12.0,
        "Containerize, deploy and add monitoring to a model-serving API.",
        (_t("model-deployment", 0.4, 0.8, True), _t("ml-monitoring", 0.3, 0.6, False),),
        (("mlops-fundamentals", 0.4), ("docker-containers", 0.4),), 0.82,
        modality="project",
    ),
)
