// Bundled demo roadmap — the exact "Become a Machine Learning Engineer" target,
// fully populated with resources, assessments, projects and prerequisites so the
// roadmap interface renders meaningfully out of the box. Shape-identical to what
// `buildRoadmapView` produces from the API.

import type { RoadmapPhase, RoadmapResource, RoadmapView } from "@/lib/roadmap-view";

const res = (r: Partial<RoadmapResource> & Pick<RoadmapResource, "id" | "title" | "status">): RoadmapResource => ({
  kind: "resource",
  type: "course",
  provider: "",
  description: "",
  url: "https://example.com",
  estimatedMinutes: 120,
  difficulty: 3,
  skills: [],
  prerequisites: [],
  why: "",
  isOptional: false,
  ...r,
});

const foundations: RoadmapPhase = {
  index: 0,
  title: "Foundations",
  objective: "Statistics and the math that underpins machine learning.",
  isCapstone: false,
  state: "completed",
  estimatedMinutes: 1500,
  completionPct: 100,
  milestones: [
    {
      id: "statistics",
      title: "Statistics",
      skill: "Statistics",
      // A completed milestone has, by definition, reached its target — the
      // demo data used to claim completion at 0.65 against a 0.8 target.
      state: "completed",
      current: 0.83,
      required: 0.8,
      completionPct: 100,
      estimatedMinutes: 1500,
      completionCriteria: "Score 70% on the Statistics checkpoint.",
      prerequisites: [],
      requiredSkills: ["Statistics", "Probability"],
      resources: [
        res({
          id: "stats-course",
          title: "Statistics for Data Science",
          type: "course",
          provider: "MockAcademy",
          description: "Descriptive and inferential statistics, distributions, hypothesis testing and confidence intervals with hands-on notebooks.",
          url: "https://example.com/stats",
          estimatedMinutes: 900,
          difficulty: 2,
          skills: ["Statistics", "Probability"],
          prerequisites: ["Python"],
          why: "Builds the statistical foundation every later ML topic assumes; matched your goal's Statistics requirement.",
          status: "completed",
        }),
        res({
          id: "stats-reading",
          title: "Think Stats (chapters 1–6)",
          type: "book",
          provider: "Open textbook",
          description: "A programmer-friendly introduction to exploratory data analysis and probability.",
          url: "https://example.com/think-stats",
          estimatedMinutes: 600,
          difficulty: 2,
          skills: ["Statistics"],
          prerequisites: ["Python"],
          why: "Reinforces the course with code-first examples at your reading level.",
          status: "completed",
        }),
      ],
      assessment: {
        id: "stats-check",
        title: "Statistics checkpoint",
        estimatedMinutes: 45,
        passingPct: 0.7,
        status: "completed",
      },
      project: null,
    },
  ],
};

const ml: RoadmapPhase = {
  index: 1,
  title: "Machine Learning",
  objective: "Core supervised and unsupervised learning.",
  isCapstone: false,
  state: "completed",
  estimatedMinutes: 3600,
  completionPct: 100,
  milestones: [
    {
      id: "machine-learning",
      title: "Machine Learning",
      skill: "Machine Learning",
      state: "completed",
      current: 0.88,
      required: 0.85,
      completionPct: 100,
      estimatedMinutes: 3600,
      completionCriteria: "Pass the ML foundations assessment (70%).",
      prerequisites: ["Statistics"],
      requiredSkills: ["Machine Learning", "Statistics"],
      resources: [
        res({
          id: "ml-course",
          title: "Machine Learning Specialization",
          type: "course",
          provider: "Coursera",
          description: "Linear and logistic regression, decision trees, ensembles, clustering and the bias–variance tradeoff.",
          url: "https://example.com/ml-spec",
          estimatedMinutes: 3000,
          difficulty: 3,
          skills: ["Machine Learning"],
          prerequisites: ["Statistics", "Python"],
          why: "The canonical path from statistics into applied ML; advanced your ML skill to 75%.",
          status: "completed",
        }),
        res({
          id: "ml-project",
          title: "Predict House Prices",
          type: "project",
          provider: "MockLabs",
          description: "An end-to-end regression project: feature engineering, model selection and evaluation.",
          url: "https://example.com/house-prices",
          estimatedMinutes: 600,
          difficulty: 3,
          skills: ["Machine Learning"],
          prerequisites: ["Machine Learning"],
          why: "Consolidates supervised learning with a portfolio-ready deliverable.",
          status: "completed",
        }),
      ],
      assessment: {
        id: "ml-check",
        title: "ML Foundations checkpoint",
        estimatedMinutes: 60,
        passingPct: 0.7,
        status: "completed",
      },
      project: null,
    },
  ],
};

const deepLearning: RoadmapPhase = {
  index: 2,
  title: "Deep Learning",
  objective: "Neural networks, PyTorch and convolutional networks.",
  isCapstone: false,
  state: "current",
  estimatedMinutes: 8400,
  completionPct: 35,
  milestones: [
    {
      id: "deep-learning",
      title: "Deep Learning",
      skill: "Deep Learning",
      state: "current",
      current: 0.42,
      required: 0.8,
      completionPct: 45,
      estimatedMinutes: 4800,
      completionCriteria: "Complete the DL course and score 70% on the checkpoint.",
      prerequisites: ["Machine Learning"],
      requiredSkills: ["Deep Learning", "Machine Learning"],
      resources: [
        res({
          id: "dl-spec",
          title: "Deep Learning Specialization",
          type: "course",
          provider: "Coursera",
          description: "Neural networks, optimization, regularization, and structuring deep learning projects across five courses.",
          url: "https://example.com/dl-spec",
          estimatedMinutes: 4800,
          difficulty: 4,
          skills: ["Deep Learning"],
          prerequisites: ["Machine Learning", "Python"],
          why: "Directly advances your current Deep Learning milestone from 42% toward the 80% your goal needs.",
          status: "current",
        }),
      ],
      assessment: {
        id: "dl-check",
        title: "Deep Learning checkpoint",
        estimatedMinutes: 60,
        passingPct: 0.7,
        status: "available",
      },
      project: null,
    },
    {
      id: "pytorch",
      title: "PyTorch",
      skill: "PyTorch",
      state: "available",
      current: 0.31,
      required: 0.7,
      completionPct: 20,
      estimatedMinutes: 1200,
      completionCriteria: "Finish PyTorch Fundamentals and the checkpoint.",
      prerequisites: ["Deep Learning"],
      requiredSkills: ["PyTorch", "Deep Learning"],
      resources: [
        res({
          id: "pytorch-blitz",
          title: "PyTorch 60-Minute Blitz",
          type: "tutorial",
          provider: "PyTorch",
          description: "The official fast-start tutorial: tensors, autograd, and training a small neural network end to end.",
          url: "https://example.com/pytorch-blitz",
          estimatedMinutes: 120,
          difficulty: 3,
          skills: ["PyTorch"],
          prerequisites: ["Deep Learning"],
          why: "Targets your PyTorch gap (31% → 70%). You meet all prerequisites and it starts at your level.",
          status: "available",
        }),
        res({
          id: "pytorch-docs",
          title: "PyTorch Fundamentals",
          type: "documentation",
          provider: "PyTorch",
          description: "Structured docs covering datasets, dataloaders, the training loop and model saving.",
          url: "https://example.com/pytorch-fundamentals",
          estimatedMinutes: 480,
          difficulty: 3,
          skills: ["PyTorch"],
          prerequisites: ["Deep Learning"],
          why: "Fills the practical PyTorch skills the specialization leaves out.",
          status: "available",
        }),
      ],
      assessment: {
        id: "pytorch-check",
        title: "PyTorch checkpoint",
        estimatedMinutes: 30,
        passingPct: 0.7,
        status: "locked",
      },
      project: null,
    },
    {
      id: "cnns",
      title: "CNNs",
      skill: "CNNs",
      state: "locked",
      current: 0.1,
      required: 0.7,
      completionPct: 0,
      estimatedMinutes: 2400,
      completionCriteria: "Build a CNN image classifier that beats the baseline.",
      prerequisites: ["PyTorch", "Deep Learning"],
      requiredSkills: ["CNNs", "PyTorch"],
      resources: [
        res({
          id: "cnn-course",
          title: "Convolutional Networks for Visual Recognition",
          type: "course",
          provider: "MockAcademy",
          description: "Convolutions, pooling, classic architectures (ResNet, VGG) and transfer learning for vision.",
          url: "https://example.com/cnns",
          estimatedMinutes: 1800,
          difficulty: 4,
          skills: ["CNNs"],
          prerequisites: ["PyTorch"],
          why: "Unlocks after PyTorch; the vision skills your ML Engineer goal expects.",
          status: "locked",
        }),
      ],
      assessment: null,
      project: {
        id: "cnn-project",
        title: "Train an Image Classifier in PyTorch",
        description: "Build, train and evaluate a CNN on a real image dataset, then write up the results.",
        estimatedMinutes: 600,
        skills: ["CNNs", "PyTorch"],
        status: "locked",
      },
    },
  ],
};

const production: RoadmapPhase = {
  index: 3,
  title: "Production",
  objective: "Deploy, serve and operate ML systems.",
  isCapstone: false,
  state: "locked",
  estimatedMinutes: 2400,
  completionPct: 0,
  milestones: [
    {
      id: "mlops",
      title: "MLOps",
      skill: "MLOps",
      state: "locked",
      current: 0.15,
      required: 0.6,
      completionPct: 0,
      estimatedMinutes: 2400,
      completionCriteria: "Deploy and monitor a model API in a container.",
      prerequisites: ["Deep Learning", "CNNs"],
      requiredSkills: ["MLOps", "Docker"],
      resources: [
        res({
          id: "mlops-zoomcamp",
          title: "MLOps Zoomcamp",
          type: "course",
          provider: "MockAcademy",
          description: "Experiment tracking, pipelines, deployment, and monitoring for production ML.",
          url: "https://example.com/mlops",
          estimatedMinutes: 2400,
          difficulty: 4,
          skills: ["MLOps"],
          prerequisites: ["Deep Learning"],
          why: "Recommended for your Production phase once Deep Learning is complete.",
          status: "locked",
        }),
      ],
      assessment: null,
      project: {
        id: "mlops-project",
        title: "Deploy a Model API",
        description: "Containerize a trained model behind a REST API with basic monitoring.",
        estimatedMinutes: 480,
        skills: ["MLOps"],
        status: "locked",
      },
    },
  ],
};

const capstone: RoadmapPhase = {
  index: 4,
  title: "Capstone",
  objective: "A portfolio-grade, end-to-end ML system for your goal.",
  isCapstone: true,
  state: "locked",
  estimatedMinutes: 1200,
  completionPct: 0,
  milestones: [
    {
      id: "capstone",
      title: "ML Engineering Capstone",
      skill: "ML Engineering",
      state: "locked",
      current: 0,
      required: 1,
      completionPct: 0,
      estimatedMinutes: 1200,
      completionCriteria: "Ship an end-to-end ML system: data → model → deployment → write-up.",
      prerequisites: ["MLOps", "CNNs"],
      requiredSkills: ["Machine Learning", "Deep Learning", "MLOps"],
      resources: [],
      assessment: null,
      project: {
        id: "capstone-project",
        title: "End-to-End ML System",
        description: "Combine everything: build, deploy and document a complete machine-learning application for your target role.",
        estimatedMinutes: 1200,
        skills: ["Machine Learning", "Deep Learning", "MLOps"],
        status: "locked",
      },
    },
  ],
};

export const demoRoadmap: RoadmapView = {
  goal: "Become a Machine Learning Engineer",
  role: "Machine Learning Engineer",
  progressPct: 68,
  totalPlannedHours: 292,
  phases: [foundations, ml, deepLearning, production, capstone],
};
